### ISSUE TITLE
[!] (plugin terser) SyntaxError: Unexpected token: operator (<)

### ISSUE THREAD

**Issue by snowdream** [TrySound/rollup-plugin-terser#108]
Project: 
https://github.com/snowdreamtech/ruim

Error:
```
 ruim git:(master) ✗ rollup -c rollup.config.prod..js 

src/components/helloworld/HelloWorld.tsx → dist/helloworld/helloworld.umd.js, dist/helloworld/helloworld.esm.js, dist/helloworld/helloworld.iife.js...
created dist/helloworld/helloworld.umd.js, dist/helloworld/helloworld.esm.js, dist/helloworld/helloworld.iife.js in 3.6s

src/components/helloworld/HelloWorld.tsx → dist/helloworld/helloworld.umd.min.js, dist/helloworld/helloworld.esm.min.js, dist/helloworld/helloworld.iife.min.js...
  45 |               count.value++;
  46 |           };
> 47 |           return () => (<>
     |                        ^ Unexpected token: operator (<)
  48 |           <h1>{msg}</h1>
  49 |
  50 |           <p>
[!] (plugin terser) SyntaxError: Unexpected token: operator (<)
SyntaxError: Unexpected token: operator (<)
    at js_error (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:3294:19)
    at expr_ops (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:3427:20)
    at expression (/Users/snowdream/workspace/snowdreamtech/self/ruim/node_modules/terser/dist/bundle.min.js:3452:24)
```

**Comment by TrySound** [comment]
Looks like typescript plugin did not transpile jsx. Clearly not rollup-plugin-terser issue.
