### ISSUE TITLE
[!] (plugin terser) TypeError: Cannot read property 'references' of undefined

### ISSUE THREAD

**Issue by mengdu** [TrySound/rollup-plugin-terser#60]
**devDependencies**
```json
{
"devDependencies": {
    "eslint": "^6.6.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "jest": "^24.9.0",
    "rollup": "^1.27.3",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-terser": "^5.1.3"
  }
}
```
**rullup.config.js**
```js
const resolve = require('rollup-plugin-node-resolve')
const commonjs = require('rollup-plugin-commonjs')
const { terser } = require('rollup-plugin-terser')
const pkg = require('./package.json')

module.exports = {
  input: 'src/index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs'
    }
  ],
  plugins: [
    resolve(),
    commonjs(),
    terser()
  ]
}
```
```
$ npm run build

> func@0.1.0 build G:\work\func
> rollup -c --environment NODE_ENV:production


src/index.js → dest/index.js...
    Cannot read property 'references' of undefined

[!] (plugin terser) TypeError: Cannot read property 'references' of undefined
TypeError: Cannot read property 'references' of undefined
    at vn.O [as before] (G:\work\func\node_modules\terser\dist\bundle.min.js:1:136818)
    at AST_Expansion.transform (G:\work\func\node_modules\terser\dist\bundle.min.js:1:78900)
    at G:\work\func\node_modules\terser\dist\bundle.min.js:1:79062
    at l (G:\work\func\node_modules\terser\dist\bundle.min.js:1:834)
```

**Comment by TrySound** [comment]
the error comes from terser package. this plugin is a thing wrapper. could you open the issue there?

**Comment by mengdu** [comment]
Okay, I got it wrong.
