### ISSUE TITLE
v6 breaks my build

### ISSUE THREAD

**Issue by nhoizey** [TrySound/rollup-plugin-terser#79]
I'm really new to Rollup, but I did manage to make it work, and `rollup-plugin-terser` v6 breaks my build. I don't know if this is because I use something that was already not supposed to work, or if this new version requires me to change something in my Rollup configuration or my JavaScript code.

Here is the error message I get when running Rollup with [my current configuration](https://github.com/nhoizey/nicolas-hoizey.com/blob/ab3aedc021b81c965b165f7e7c680de86009723e/rollup.config.js) and `rollup-plugin-terser` version 6.0.0 or 6.1.0:

```
[!] Error: No valid exports main found for '/Users/nhoizey/Documents/Devs/@perso/nicolas-hoizey.com/node_modules/rollup-plugin-terser'
Error: No valid exports main found for '/Users/nhoizey/Documents/Devs/@perso/nicolas-hoizey.com/node_modules/rollup-plugin-terser'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nhoizey/Documents/Devs/@perso/nicolas-hoizey.com/rollup.config.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nicolas-hoizey.com@2.3.0 assets:build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nicolas-hoizey.com@2.3.0 assets:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nhoizey/.npm/_logs/2020-06-01T22_09_54_009Z-debug.log
ERROR: "assets:build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Here is the content of the log file:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/nhoizey/.nvm/versions/node/v13.6.0/bin/node',
1 verbose cli   '/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'assets:build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v13.6.0
4 verbose run-script [ 'preassets:build', 'assets:build', 'postassets:build' ]
5 info lifecycle nicolas-hoizey.com@2.3.0~preassets:build: nicolas-hoizey.com@2.3.0
6 info lifecycle nicolas-hoizey.com@2.3.0~assets:build: nicolas-hoizey.com@2.3.0
7 verbose lifecycle nicolas-hoizey.com@2.3.0~assets:build: unsafe-perm in lifecycle true
8 verbose lifecycle nicolas-hoizey.com@2.3.0~assets:build: PATH: /Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/nhoizey/Documents/Devs/@perso/nicolas-hoizey.com/node_modules/.bin:/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/nhoizey/Documents/Devs/@perso/nicolas-hoizey.com/node_modules/.bin:/Users/nhoizey/.nvm/versions/node/v13.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/nhoizey/.rvm/bin
9 verbose lifecycle nicolas-hoizey.com@2.3.0~assets:build: CWD: /Users/nhoizey/Documents/Devs/@perso/nicolas-hoizey.com
10 silly lifecycle nicolas-hoizey.com@2.3.0~assets:build: Args: [ '-c', 'rollup -c' ]
11 silly lifecycle nicolas-hoizey.com@2.3.0~assets:build: Returned: code: 1  signal: null
12 info lifecycle nicolas-hoizey.com@2.3.0~assets:build: Failed to exec assets:build script
13 verbose stack Error: nicolas-hoizey.com@2.3.0 assets:build: `rollup -c`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid nicolas-hoizey.com@2.3.0
15 verbose cwd /Users/nhoizey/Documents/Devs/@perso/nicolas-hoizey.com
16 verbose Darwin 19.4.0
17 verbose argv "/Users/nhoizey/.nvm/versions/node/v13.6.0/bin/node" "/Users/nhoizey/.nvm/versions/node/v13.6.0/lib/node_modules/npm/bin/npm-cli.js" "run" "assets:build"
18 verbose node v13.6.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error nicolas-hoizey.com@2.3.0 assets:build: `rollup -c`
22 error Exit status 1
23 error Failed at the nicolas-hoizey.com@2.3.0 assets:build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by TrySound** [comment]
Please upgrade your node to the latest v13. 13.6 is very old one.

**Comment by nhoizey** [comment]
It works with Node.js 13.14.0 indeed, thanks! 👍
