### ISSUE TITLE
TypeError: child.send is not a function

### ISSUE THREAD

**Issue by maxzhang666** [TrySound/rollup-plugin-terser#80]
Hi there

when i run 'rollup -c' ,i got this error

```
[!] (plugin terser) TypeError: child.send is not a function
TypeError: child.send is not a function
    at ChildProcessWorker.initialize (/Users/maxzhang/Documents/dothings/node_modules/jest-worker/build/workers/ChildProcessWorker.js:179:11)
    at new ChildProcessWorker (/Users/maxzhang/Documents/dothings/node_modules/jest-worker/build/workers/ChildProcessWorker.js:130:10)
    at WorkerPool.createWorker (/Users/maxzhang/Documents/dothings/node_modules/jest-worker/build/WorkerPool.js:44:12)
    at new BaseWorkerPool (/Users/maxzhang/Documents/dothings/node_modules/jest-worker/build/base/BaseWorkerPool.js:134:27)
    at new WorkerPool (/Users/maxzhang/Documents/dothings/node_modules/jest-worker/build/WorkerPool.js:30:1)
    at new JestWorker (/Users/maxzhang/Documents/dothings/node_modules/jest-worker/build/index.js:112:26)
    at Object.renderChunk (/Users/maxzhang/Documents/dothings/node_modules/rollup-plugin-terser/rollup-plugin-terser.js:22:23)
    at Promise.resolve.then (/Users/maxzhang/Documents/dothings/node_modules/rollup/dist/shared/rollup.js:18130:25)
```

but,it does not appear often

Can help me find the problem

npm version:6.14.5
```
"dependencies": {
    "@types/echarts": "^4.6.2",
    "@types/jquery": "^3.3.38",
    "@types/qrcode": "^1.3.4",
    "@types/tampermonkey": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "vue": "^2.6.11",
    "rollup": "^2.0.0",
    "terser": "^4.7.0",
    "@rollup/plugin-node-resolve": "^7.1.3",
    "rollup-plugin-cleanup": "^3.1.1",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-license": "^2.1.0",
    "rollup-plugin-sourcemaps": "^0.5.0",
    "rollup-plugin-terser": "^6.1.0",
    "rollup-plugin-typescript": "^1.0.1",
    "sweetalert2": "^9.15.1",
    "ts-lint": "^4.5.1",
    "ts-loader": "^5.3.3",
    "tslib": "^1.13.0",
    "tslint": "^5.11.0",
    "tslint-loader": "^3.5.4",
    "typescript": "^3.9.5"
  }
```

**Comment by TrySound** [comment]
What is your node.js version?

**Comment by maxzhang666** [comment]
> What is your node.js version?

v10.16.3

**Comment by TrySound** [comment]
I found very similar problem.
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/254

**Comment by maxzhang666** [comment]
Thank you
I found it was caused by too many background tasks
When my computer is idle, there will be no such anomaly
