### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by caixianglin** [TrySound/rollup-plugin-terser#83]
node v8.16.1
const { terser } = require('rollup-plugin-terser')

reason:  /Users/***/node_modules/jest-worker/build/WorkerPool.js:25
  } catch {
          ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/***/node_modules/jest-worker/build/index.js:18:42)

node v10.x.x
正常

**Comment by TrySound** [comment]
I guess terser do not support this syntax yet. You should transpile your code with babel or typescript.
