### ISSUE TITLE
Unhandled drop_console

### ISSUE THREAD

**Issue by GrosSacASac** [TrySound/rollup-plugin-terser#97]
```js
import { terser } from "rollup-plugin-terser";
import __package from "../package.json";

const VERSION = __package.version;
const GLOBAL_NAME = `d`;

const commonOutputOptions = {
    name: GLOBAL_NAME,
    banner: `/* dom99 v${VERSION} */
	/*        Copyright Cyril Walle
Distributed under the Boost Software License, Version 1.0.
    See accompanying file LICENSE.txt or copy at
         https://www.boost.org/LICENSE_1_0.txt */
`,
    // footer: ``,
    // intro: ``,
    // outro: ``,
    interop: false,
    extend: false,
    strict: true,
    namespaceToStringTag: false
};

export default [{
    input: `source/dom99.js`,
    treeshake: {
        propertyReadSideEffects: false // assume reading properties has no side effect
    },
    output: [
        Object.assign({
            format: `es`,
            file: `built/dom99.es.min.js`,
        }, commonOutputOptions),
    ],

    watch: {
        clearScreen: true
    },
    plugins: [terser({
        drop_console: true,
    })]
}];
```

  `drop_console` is not a supported option

[!] (plugin terser) DefaultsError: `drop_console` is not a supported option
DefaultsError: `drop_console` is not a supported option
    at defaults (C:\files\github\DOM99\node_modules\terser\dist\bundle.min.js:82:15)
    at minify (C:\files\github\DOM99\node_modules\terser\dist\bundle.min.js:25971:15)
    at Object.transform (C:\files\github\DOM99\node_modules\rollup-plugin-terser\transform.js:5:10)
    at execFunction (C:\files\github\DOM99\node_modules\jest-worker\build\workers\processChild.js:145:17)
    at execHelper (C:\files\github\DOM99\node_modules\jest-worker\build\workers\processChild.js:124:5)
    at execMethod (C:\files\github\DOM99\node_modules\jest-worker\build\workers\processChild.js:128:5)
    at process.messageListener (C:\files\github\DOM99\node_modules\jest-worker\build\workers\processChild.js:46:7)
    at process.emit (node:events:327:20)
    at emit (node:internal/child_process:903:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

If I comment out drop_console it works

**Comment by GrosSacASac** [comment]
Steps to reproduce:
Clone https://github.com/GrosSacASac/DOM99, npm i , uncomment drop_console, npm run bundle

**Comment by TrySound** [comment]
Try `compress: {drop_console: true}`
